---
title: "Spillane_316_Week_8"
author: "Patrick Spillane"
date: "2023-07-19"
output: html_document
---
```{r}
#1A
(22*5/9)+32 #This is the formula of turning 22 degrees Celsius into the degrees in Fahrenheit
```

```{r}
#1B
celsius<-22#This is to make it so that Degrees Celsius represents the number 22 and replaces it in the equation for the function
fahrenheit<- (celsius*5/9)+32 #This is to show the equation for converting Celsius to Fahrenheit
for (x in celsius) {
  celsius_to_fahrenheitbeta<-(x * 5/9)+32 #This makes it so that the number that represents degrees in Fahrenheit, in this example being 22, will be represented by x. 
}
celsius_to_fahrenheitbeta#This is for the test to run and see if it is done correctly
```

```{r}
#1C
celsius_to_fahrenheit <- function(C){ 
  F <- ((C * 5/9) +32) #This makes F (which means Fahrenheit) equal the degrees in Celsius 
  
  temp_simplify <- round(x = F, digits= 0)#This makes it so that the degrees in Fahrenheit is rounded down to a whole number
  
  return(temp_simplify) #This tells the user of this function what is to be given as the end result of the function
 
}
```

```{r}
#1D
celsius_to_fahrenheit(C= c(5, 35)) #This is to check if the newly made function works, and by the testing it seems that it does work, it converts both numbers into the degrees in Fahrenheit
```